# fly.toml app configuration file generated for astro-pb on 2023-07-16T09:51:50+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "astro-pb"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"